@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user

box UI UI_COLOR_1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FairShareParser" as FairShareParser LOGIC_COLOR
participant "e:ExitCommand" as ExitCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

user -> MainWindow : inputs "exit"
activate MainWindow

MainWindow -> LogicManager : execute("exit")
activate LogicManager

LogicManager -> FairShareParser : parseCommand("exit")
activate FairShareParser

create ExitCommand
FairShareParser -> ExitCommand : new
activate ExitCommand

ExitCommand --> FairShareParser : e
deactivate ExitCommand

FairShareParser --> LogicManager : e
deactivate FairShareParser

LogicManager -> ExitCommand : execute(m)
activate ExitCommand

create CommandResult
ExitCommand -> CommandResult : new("Shutting down FairShare...", false, true)
activate CommandResult
CommandResult --> ExitCommand : r
deactivate CommandResult

ExitCommand --> LogicManager : r
deactivate ExitCommand

LogicManager --> MainWindow : r
deactivate LogicManager

MainWindow -> MainWindow : handleExit()
MainWindow --> user : application closes after delay
deactivate MainWindow
@enduml
