@startuml
allowmixing
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam nodesep 80
skinparam ranksep 80

Package "Shared Expense Tracker" <<Rectangle>> {
    Component UI
    Component Logic
    Component Storage
    Component Model
    Component Main
}

Rectangle User
File "Text File" as textFile

User .right.> UI

UI -> Logic
UI .down.> Model

Logic -down-> Storage
Logic -down-> Model

Main -up-> UI
Main -up-> Logic
Main -right-> Model
Main -down-> Storage

Storage -up.> Model
Storage .right.> textFile

@enduml